name: Docker Build

on:
  push:
    branches:
      - master

jobs:
  docker-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t zero-touch-dashboard .

      - name: Trivy Security Scan
        uses: aquasecurity/trivy-action@v0.35.0
        with:
          image-ref: zero-touch-dashboard
          severity: CRITICAL,HIGH
          exit-code: '1'
